### ISSUE TITLE
improper token

### ISSUE THREAD

**Issue by Whxyuu** [itskekoff/discord-server-copy#10]
can you add the bot=False at the end of the code
Example : bot.run(token, bot=False)
or else your code cant run

**Comment by itskekoff** [comment]
Make sure you use discord.py-self instead of discord.py. My code uses discord.py-self and everything works fine.
Also check which token you put in the config. The token you put in is probably not valid.

**Comment by imhasnain** [comment]
* Updates doesn't found.
Traceback (most recent call last):
  File "C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\discord\http.py", line 418, in static_login
    data = await self.request(Route("GET", "/users/@me"))
           AGVDbNVutgwiep6615bjTJnQkScwWuUEMuU95NredRG5^^^
  File "C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\discord\http.py", line 371, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\dell\Desktop\discord-server-copy-main\discord-server-copy-main\main.py", line 387, in <module>
    bot.run(token)
  File "C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 717, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 696, in runner
    await self.start(*args, **kwargs)
  File "C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 659, in start
    await self.login(token)
  File "C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\discord\client.py", line 515, in login
    data = await self.http.static_login(token.strip())
           AGVDbNVutgwiep6615bjTJnQkScwWuUEMuU95NredRG5
  File "C:\Users\dell\AppData\Roaming\Python\Python311\site-packages\discord\http.py", line 422, in static_login
    raise LoginFailure("Improper token has been passed.") from exc
discord.errors.LoginFailure: Improper token has been passed.

> Make sure you use discord.py-self instead of discord.py. My code uses discord.py-self and everything works fine. Also check which token you put in the config. The token you put in is probably not valid.

**Comment by itskekoff** [comment]
Check the token you specified in the config. You may have set the bot's token instead of your discord token. It is important to know that this is not a bot, but a self bot, i.e. makes a bot out of a user, not a bot out of a bot.
