### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xivgit** [itskekoff/discord-server-copy#18]
[2023-05-15 18:48:08] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command copy
Traceback (most recent call last):
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "main.py", line 356, in copy
    guild: discord.Guild = bot.get_guild(id=server_id) if server_id else ctx.message.guild
TypeError: get_guild() got some positional-only arguments passed as keyword arguments: 'id'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python38\lib\site-packages\discord\ext\commands\core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: get_guild() got some positional-only arguments passed as keyword arguments: 'id'

**Comment by xivgit** [comment]
That is when i try to cp!clone (id server)

**Comment by itskekoff** [comment]
Fixed.

**Comment by xivgit** [comment]
ty
