### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by xivgit** [itskekoff/discord-server-copy#19]
[2023-05-15 19:33:52] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command copy
Traceback (most recent call last):
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\xiv\Desktop\discordcopy\discord-server-copy-main\main.py", line 373, in copy
    await cloner.clone_channels(perms=clone_permissions)
  File "C:\Users\xiv\Desktop\discordcopy\discord-server-copy-main\main.py", line 223, in clone_channels
    overwrites[self.mappings["roles"][role]] = permissions
KeyError: <Object id=235148962103951360 type=<class 'discord.abc.User'>>

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: <Object id=235148962103951360 type=<class 'discord.abc.User'>>

**Comment by xivgit** [comment]
[2023-05-15 20:17:56] [ERROR   ] discord.ext.commands.bot: Ignoring exception in command copy
Traceback (most recent call last):
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\xiv\Desktop\discordcopy\discord-server-copy-main\main.py", line 373, in copy
    await cloner.clone_channels(perms=clone_permissions)
  File "C:\Users\xiv\Desktop\discordcopy\discord-server-copy-main\main.py", line 254, in clone_channels
    new_channel = await self.new_guild.create_stage_channel(name=channel.name, topic=channel.topic,
TypeError: create_stage_channel() got an unexpected keyword argument 'topic'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "C:\Users\xiv\AppData\Local\Programs\Python\Python39\lib\site-packages\discord\ext\commands\core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: create_stage_channel() got an unexpected keyword argument 'topic'

**Comment by xivgit** [comment]
There is also that when i lauch.

[2023-05-15 20:16:53] [WARNING ] discord.state: Member list scraping failed for 1102353551327506462 (Failed to automatically choose channels; please specify them manually).
[2023-05-15 20:16:53] [WARNING ] discord.state: Member list scraping failed for 1102631210880086056 (Failed to automatically choose channels; please specify them manually).

**Comment by itskekoff** [comment]
what version of python and discord.py-self are you using?

**Comment by itskekoff** [comment]
> i'm using Python 3.9 and idk for the discord.py-self
     `pip uninstall discord.py-self`
try `pip install discord.py-self==1.9.2`

**Comment by xivgit** [comment]
sry but not working

**Comment by itskekoff** [comment]
> sry but not working

same error?

**Comment by itskekoff** [comment]
> There is also that when i launch.
> 
> [2023-05-15 20:16:53] [WARNING ] discord.state: Member list scraping failed for 1102353551327506462 (Failed to automatically choose channels; please specify them manually). [2023-05-15 20:16:53] [WARNING ] discord.state: Member list scraping failed for 1102631210880086056 (Failed to automatically choose channels; please specify them manually).

for discord.py-self this is normal.

**Comment by itskekoff** [comment]
now fixed in 1.3 update. Delete your config and download update from this repository.
