### ISSUE TITLE
Error when I run python3 main.py

### ISSUE THREAD

**Issue by Fluff4life** [itskekoff/discord-server-copy#20]
File "/Users/juneychan/Downloads/discord-server-copy-main/main.py", line 406, in <module>
    bot.run(token, log_handler=file_handler, log_formatter=formatter)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/client.py", line 631, in run
    return future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/client.py", line 610, in runner
    await self.start(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/discord/client.py", line 571, in start
    raise TypeError("unexpected keyword argument(s) %s" % list(kwargs.keys()))
TypeError: unexpected keyword argument(s) ['log_handler', 'log_formatter']

**Comment by itskekoff** [comment]
make sure that u using discord.py-self instead of discord.py

**Comment by Fluff4life** [comment]
> make sure that u using discord.py-self instead of discord.py

now it says " from discord.ext import commands
ImportError: cannot import name 'commands' from 'discord.ext' (unknown location)"

**Comment by Fluff4life** [comment]
> > make sure that u using discord.py-self instead of discord.py
> 
> now it says " from discord.ext import commands ImportError: cannot import name 'commands' from 'discord.ext' (unknown location)"
Should I type pip3 install discord.py-self or pip install discord.py-self
I am now using Python 10

**Comment by Fluff4life** [comment]
I got it working, but It's stuck on creating server. There is no error, but it just is stuck on creating server

**Comment by itskekoff** [comment]
> I got it working, but It's stuck on creating server. There is no error, but it just is stuck on creating server

error log saved in .log file (27.05.2023-discord.log). show me it so i can fix that shit

**Comment by Fluff4life** [comment]
> > I got it working, but It's stuck on creating server. There is no error, but it just is stuck on creating server
> 
> error log saved in .log file (27.05.2023-discord.log). show me it so i can fix that shit

2023-05-27 03:56:30,739 | INFO | Logging in using static token.
2023-05-27 03:56:31,441 | INFO | Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36, build number 199933.
2023-05-27 03:56:34,216 | INFO | Connected to Gateway (Session ID: f533e49de44b0f24169ea049c52c8de3).
2023-05-27 03:56:34,907 | WARNING | Member list scraping failed for 668080381094002688 (Failed to automatically choose channels; please specify them manually).
2023-05-27 03:56:34,907 | WARNING | Member list scraping failed for 805833894636421151 (Failed to automatically choose channels; please specify them manually).
2023-05-27 03:56:34,908 | WARNING | Member list scraping failed for 1022803713020145685 (Failed to automatically choose channels; please specify them manually).
2023-05-27 03:56:34,908 | WARNING | Member list scraping failed for 1101608759714910249 (Failed to automatically choose channels; please specify them manually).
2023-05-27 03:56:34,909 | WARNING | Member list scraping failed for 928222962413367386 (Failed to automatically choose channels; please specify them manually).
2023-05-27 03:56:34,910 | WARNING | Gateway is ratelimited, waiting 57.79 seconds.
2023-05-27 03:56:34,911 | WARNING | Member list scraping failed for 971536577312489495 (Failed to automatically choose channels; please specify them manually).
2023-05-27 03:56:46,945 | WARNING | Timed out waiting for member list subscriptions for guild_id 758782745647382540.
2023-05-27 03:56:47,516 | ERROR | Ignoring exception in command copy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/juneychan/Downloads/discord-server-copy-main/main.py", line 371, in copy
    new_guild: discord.Guild = await bot.create_guild(name_syntax.replace("%original", guild.name))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 1785, in create_guild
    data = await self.http.create_guild(name, icon_base64)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 830, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 10008): Unknown Message
2023-05-27 03:56:56,948 | WARNING | Timed out waiting for member list subscriptions for guild_id 1097353823334453298.
2023-05-27 03:57:06,955 | WARNING | Timed out waiting for member list subscriptions for guild_id 844325805189890048.
2023-05-27 03:57:16,957 | WARNING | Timed out waiting for member list subscriptions for guild_id 1104684336340545556.
2023-05-27 03:57:26,964 | WARNING | Timed out waiting for member list subscriptions for guild_id 1061066656849350737.
2023-05-27 06:07:07,224 | INFO | Logging in using static token.
2023-05-27 06:07:07,793 | INFO | Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36, build number 199933.
2023-05-27 06:07:09,688 | INFO | Connected to Gateway (Session ID: cc594d4251464dcbc5df00da87196d6f).
2023-05-27 06:07:10,421 | WARNING | Member list scraping failed for 668080381094002688 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:07:10,422 | WARNING | Member list scraping failed for 805833894636421151 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:07:10,422 | WARNING | Member list scraping failed for 1022803713020145685 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:07:10,422 | WARNING | Member list scraping failed for 1101608759714910249 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:07:10,423 | WARNING | Member list scraping failed for 928222962413367386 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:07:10,424 | WARNING | Gateway is ratelimited, waiting 57.66 seconds.
2023-05-27 06:07:10,424 | WARNING | Member list scraping failed for 971536577312489495 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:07:10,424 | WARNING | Member list scraping failed for 1111928327259836506 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:07:22,526 | WARNING | Timed out waiting for member list subscriptions for guild_id 1065074295115616326.
2023-05-27 06:07:32,535 | WARNING | Timed out waiting for member list subscriptions for guild_id 758782745647382540.
2023-05-27 06:07:42,545 | WARNING | Timed out waiting for member list subscriptions for guild_id 1097353823334453298.
2023-05-27 06:07:52,551 | WARNING | Timed out waiting for member list subscriptions for guild_id 844325805189890048.
2023-05-27 06:08:02,556 | WARNING | Timed out waiting for member list subscriptions for guild_id 1104684336340545556.
2023-05-27 06:08:18,390 | ERROR | Ignoring exception in command copy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/juneychan/Downloads/discord-server-copy-main/main.py", line 371, in copy
    new_guild: discord.Guild = await bot.create_guild(name_syntax.replace("%original", guild.name))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 1785, in create_guild
    data = await self.http.create_guild(name, icon_base64)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 830, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 10008): Unknown Message
2023-05-27 06:10:41,130 | INFO | Logging in using static token.
2023-05-27 06:10:41,311 | INFO | Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36, build number 199933.
2023-05-27 06:10:43,328 | INFO | Connected to Gateway (Session ID: 0cef2d79c48c31e5186ca740746fdb3f).
2023-05-27 06:10:44,163 | WARNING | Member list scraping failed for 668080381094002688 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:10:44,164 | WARNING | Member list scraping failed for 805833894636421151 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:10:44,165 | WARNING | Member list scraping failed for 1022803713020145685 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:10:44,165 | WARNING | Member list scraping failed for 1101608759714910249 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:10:44,166 | WARNING | Member list scraping failed for 928222962413367386 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:10:44,167 | WARNING | Gateway is ratelimited, waiting 57.43 seconds.
2023-05-27 06:10:44,167 | WARNING | Member list scraping failed for 971536577312489495 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:10:44,167 | WARNING | Member list scraping failed for 1111928327259836506 (Failed to automatically choose channels; please specify them manually).
2023-05-27 06:10:57,220 | WARNING | Timed out waiting for member list subscriptions for guild_id 1065074295115616326.
2023-05-27 06:11:07,222 | WARNING | Timed out waiting for member list subscriptions for guild_id 758782745647382540.
2023-05-27 06:11:17,230 | WARNING | Timed out waiting for member list subscriptions for guild_id 1097353823334453298.
2023-05-27 06:11:26,415 | ERROR | Ignoring exception in command copy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/juneychan/Downloads/discord-server-copy-main/main.py", line 371, in copy
    new_guild: discord.Guild = await bot.create_guild(name_syntax.replace("%original", guild.name))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 1785, in create_guild
    data = await self.http.create_guild(name, icon_base64)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 830, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 10008): Unknown Message
2023-05-27 06:11:27,231 | WARNING | Timed out waiting for member list subscriptions for guild_id 844325805189890048.
2023-05-27 06:11:37,232 | WARNING | Timed out waiting for member list subscriptions for guild_id 1104684336340545556.
2023-05-27 06:12:33,653 | INFO | Logging in using static token.
2023-05-27 06:12:33,895 | INFO | Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/113.0.0.0 Safari/537.36, build number 199933.
2023-05-27 06:12:35,177 | INFO | Connected to Gateway (Session ID: 28fd3b1304f285cc7f7e0fdcbaff99f4).
2023-05-27 06:12:58,263 | ERROR | Ignoring exception in command copy
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 236, in wrapped
    ret = await coro(*args, **kwargs)
  File "/Users/juneychan/Downloads/discord-server-copy-main/main.py", line 371, in copy
    new_guild: discord.Guild = await bot.create_guild(name_syntax.replace("%original", guild.name))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/client.py", line 1785, in create_guild
    data = await self.http.create_guild(name, icon_base64)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/http.py", line 830, in request
    raise Forbidden(response, data)
discord.errors.Forbidden: 403 Forbidden (error code: 10008): Unknown Message

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 1020, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/discord/ext/commands/core.py", line 245, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: Forbidden: 403 Forbidden (error code: 10008): Unknown Message

**Comment by itskekoff** [comment]
do you using cp!copy command in server or in dm? if in server, send me link to discord server so i can test it.

**Comment by Fluff4life** [comment]
> do you using cp!copy command in server or in dm? if in server, send me link to discord server so i can test it.

I did cp!clone ID and just cp!clone
I tried this server: https://discord.gg/sound

**Comment by itskekoff** [comment]
i tested and all works for me. What version of discord.py-self do you using?  Make sure that you using latest version of discord.py-self. If you using latest version, check your configuration.

**Comment by Fluff4life** [comment]
> i tested and all works for me. What version of discord.py-self do you using? Make sure that you using latest version of discord.py-self. If you using latest version, check your configuration and send me it if all right in configuration.

What is the exact command I do to install the latest version of discord.py-self? I don't know if I should be using pip3 or pip since Im using python 10

**Comment by itskekoff** [comment]
> > i tested and all works for me. What version of discord.py-self do you using? Make sure that you using latest version of discord.py-self. If you using latest version, check your configuration and send me it if all right in configuration.
> 
> What is the exact command I do to install the latest version of discord.py-self? I don't know if I should be using pip3 or pip since Im using python 10

try `python -m pip uninstall discord.py-self` and do install same way.

**Comment by Fluff4life** [comment]
> 

" No module named pip"

**Comment by itskekoff** [comment]
> > 
> 
> " No module named pip"

try to delete python completely and install it again.

**Comment by Fluff4life** [comment]
> python -m pip uninstall discord.py-self

what version do you recommend?

**Comment by itskekoff** [comment]
> > python -m pip uninstall discord.py-self
> 
> what version do you recommend?

im using python 3.9

**Comment by Fluff4life** [comment]
> > > python -m pip uninstall discord.py-self
> > 
> > 
> > what version do you recommend?
> 
> im using python 3.9

Still doesn't work. I am on MacOS so the format might be different of the command I have to run.

**Comment by itskekoff** [comment]
> > > > python -m pip uninstall discord.py-self
> > > 
> > > 
> > > what version do you recommend?
> > 
> > 
> > im using python 3.9
> 
> Still doesn't work. I am on MacOS so the format might be different of the command I have to run.

try use `pip install discord.py-self`

**Comment by Fluff4life** [comment]
> > > > > python -m pip uninstall discord.py-self
> > > > 
> > > > 
> > > > what version do you recommend?
> > > 
> > > 
> > > im using python 3.9
> > 
> > 
> > Still doesn't work. I am on MacOS so the format might be different of the command I have to run.
> 
> try use `pip install discord.py-self`

I figured it out. It's cloning now. Thank u! <3

**Comment by itskekoff** [comment]
> > > > > > python -m pip uninstall discord.py-self
> > > > > 
> > > > > 
> > > > > what version do you recommend?
> > > > 
> > > > 
> > > > im using python 3.9
> > > 
> > > 
> > > Still doesn't work. I am on MacOS so the format might be different of the command I have to run.
> > 
> > 
> > try use `pip install discord.py-self`
> 
> I figured it out. It's cloning now. Thank u! <3

np

**Comment by eduDev81** [comment]
hey having the same problem here....on a Macbook with python 3.10.9 and discord.py-self 1.9.2 installed, still getting the error: TypeError: unexpected keyword argument(s) ['log_handler', 'log_formatter']

How did you solve that?
