### ISSUE TITLE
Update’s dosen’t found??

### ISSUE THREAD

**Issue by van1shco** [itskekoff/discord-server-copy#32]
05:03:21 | INFO     | Updates doesn't found.
Traceback (most recent call last):
  File "/home/runner/discord-server-copy-1/main.py", line 404, in <module>
    bot.run(token, log_handler=file_handler, log_formatter=formatter)
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 938, in run
    asyncio.run(runner())
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 927, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 857, in start
    await self.login(token)
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 698, in login
    data = await state.http.static_login(token.strip())
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/http.py", line 994, in static_login
    data = await self.get_me()
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/http.py", line 772, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 429 Too Many Requests (error code: 0): selfbots are against Discord's terms of service

**Comment by itskekoff** [comment]
"updates doesnt found" not an error. just checks version from github.

for error below, idk. try update discord.py-self or wait 10-15 minutes

**Comment by van1shco** [comment]
not work

**Comment by itskekoff** [comment]
> not work
if this happens when running on PC, use any vps/vds. discord blocking it.

**Comment by van1shco** [comment]
I ran it on replit it still didn’t work!!
