### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by van1shco** [itskekoff/discord-server-copy#34]
07:03:26 | INFO     | Updates doesn't found.
Traceback (most recent call last):
  File "/home/runner/discord-server-copy-1/main.py", line 405, in <module>
    bot.run(token, log_handler=file_handler, log_formatter=formatter)
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 938, in run
    asyncio.run(runner())
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/nix/store/xf54733x4chbawkh1qvy9i1i4mlscy1c-python3-3.10.11/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 927, in runner
    await self.start(token, reconnect=reconnect)
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 857, in start
    await self.login(token)
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/client.py", line 698, in login
    data = await state.http.static_login(token.strip())
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/http.py", line 991, in static_login
    await self.startup()
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/http.py", line 562, in startup
    self.super_properties, self.encoded_super_properties = sp, _ = await utils._get_info(session)
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/utils.py", line 1446, in _get_info
    bn = await _get_build_number(session)
  File "/home/runner/discord-server-copy-1/.pythonlibs/lib/python3.10/site-packages/discord/utils.py", line 1478, in _get_build_number
    return int(build_file[build_index : build_index + 6])
ValueError: invalid literal for int() with base 10: 'ER_V2_'

**Comment by itskekoff** [comment]
package issue. write to author of discord.py-self
