### ISSUE TITLE
Error in startup

### ISSUE THREAD

**Issue by Hacker228342** [itskekoff/discord-server-copy#36]
[09-12-2023-discord.log](https://github.com/itskekoff/discord-server-copy/files/13625421/09-12-2023-discord.log)
[09-12-2023.log](https://github.com/itskekoff/discord-server-copy/files/13625422/09-12-2023.log)

**Hi, I encountered an error at startup.**

22:12:58 | INFO     | Updates doesn't found.
Traceback (most recent call last):
  File "main.py", line 405, in <module>
    bot.run(token, log_handler=file_handler, log_formatter=formatter)
  File "D:\Новая папка\lib\site-packages\discord\client.py", line 938, in run
    asyncio.run(runner())
  File "D:\Новая папка\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "D:\Новая папка\lib\asyncio\base_events.py", line 608, in run_until_complete
    return future.result()
  File "D:\Новая папка\lib\site-packages\discord\client.py", line 927, in runner
    await self.start(token, reconnect=reconnect)
  File "D:\Новая папка\lib\site-packages\discord\client.py", line 857, in start
    await self.login(token)
  File "D:\Новая папка\lib\site-packages\discord\client.py", line 698, in login
    data = await state.http.static_login(token.strip())
  File "D:\Новая папка\lib\site-packages\discord\http.py", line 991, in static_login
    await self.startup()
  File "D:\Новая папка\lib\site-packages\discord\http.py", line 562, in startup
    self.super_properties, self.encoded_super_properties = sp, _ = await utils._get_info(session)
  File "D:\Новая папка\lib\site-packages\discord\utils.py", line 1446, in _get_info
    bn = await _get_build_number(session)
  File "D:\Новая папка\lib\site-packages\discord\utils.py", line 1474, in _get_build_number
    build_url = 'https://discord.com/assets/' + re.compile(r'assets/+([a-z0-9]+)\.js').findall(login_page)[-2] + '.js'
IndexError: list index out of range
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021FF78FA040>
Traceback (most recent call last):
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Новая папка\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "D:\Новая папка\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021FF78FA040>
Traceback (most recent call last):
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Новая папка\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "D:\Новая папка\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021FF78FA040>
Traceback (most recent call last):
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Новая папка\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "D:\Новая папка\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021FF78FA040>
Traceback (most recent call last):
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Новая папка\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "D:\Новая папка\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed
Exception ignored in: <function _ProactorBasePipeTransport.__del__ at 0x0000021FF78FA040>
Traceback (most recent call last):
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 116, in __del__
    self.close()
  File "D:\Новая папка\lib\asyncio\proactor_events.py", line 108, in close
    self._loop.call_soon(self._call_connection_lost, None)
  File "D:\Новая папка\lib\asyncio\base_events.py", line 711, in call_soon
    self._check_closed()
  File "D:\Новая папка\lib\asyncio\base_events.py", line 504, in _check_closed
    raise RuntimeError('Event loop is closed')
RuntimeError: Event loop is closed

**Comment by itskekoff** [comment]
исправлено в новой версии
