### ISSUE TITLE
why?

### ISSUE THREAD

**Issue by reallmerry** [itskekoff/discord-server-copy#49]
Traceback (most recent call last):
  File "main.py", line 14, in <module>
    from modules.configuration import Configuration
  File "C:\Users\stepa\OneDrive\Рабочий стол\discord-server-copy-main\modules\configuration.py", line 7, in <module>
    class Configuration:
  File "C:\Users\stepa\OneDrive\Рабочий стол\discord-server-copy-main\modules\configuration.py", line 29, in Configuration
    def write(self, keys: List[Any] | str, value: Any):
TypeError: unsupported operand type(s) for |: '_GenericAlias' and 'type'

help pls:(

**Comment by itskekoff** [comment]
update python to newer version
