### ISSUE TITLE
Ошибка когда создаются каналы:

### ISSUE THREAD

**Issue by Xota6bi4h** [itskekoff/discord-server-copy#6]
Ignoring exception in command copy:
Traceback (most recent call last):
  File "C:\Users\Степа\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 85, in wrapped
    ret = await coro(*args, **kwargs)
  File "C:\Users\Степа\Desktop\discord-server-copy-main\main.py", line 374, in copy
    await cloner.clone_channels(perms=clone_permissions)
  File "C:\Users\Степа\Desktop\discord-server-copy-main\main.py", line 239, in clone_channels
    new_channel = await self.new_guild.create_voice_channel(name=channel.name, position=channel.position,
  File "C:\Users\Степа\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\guild.py", line 1118, in create_voice_channel
    data = await self._create_channel(name, overwrites, ChannelType.voice, category, **options)
  File "C:\Users\Степа\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\http.py", line 302, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In bitrate: int value should be less than or equal to 96000.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Степа\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\bot.py", line 939, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\Степа\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 863, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "C:\Users\Степа\AppData\Local\Programs\Python\Python310\lib\site-packages\discord\ext\commands\core.py", line 94, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: HTTPException: 400 Bad Request (error code: 50035): Invalid Form Body
In bitrate: int value should be less than or equal to 96000.

**Comment by Xota6bi4h** [comment]
![image](https://user-images.githubusercontent.com/97909867/222342610-9ba5566e-b786-48cd-9f02-13fa97757fce.png)

**Comment by itskekoff** [comment]
Исправил
