### ISSUE TITLE
Processing server categories... Bug

### ISSUE THREAD

**Issue by m2k7m** [itskekoff/discord-server-copy#63]
if you have a discord server ill send you a log but anyway, bot stop working when its reach Processing server categories... log
``` bash
2024-05-17 02:32:04,675 | INFO | Logging in using static token.
2024-05-17 02:32:05,452 | INFO | Found user agent Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/125.0.0.0 Safari/537.36, build number 294150.
2024-05-17 02:32:06,800 | INFO | Connected to Gateway (Session ID: 43c6e34ec378f0a4f974913c77002060).
2024-05-17 02:32:47,477 | ERROR | Ignoring exception in command copy
Traceback (most recent call last):
  File "C:\Users\ALMWSHOOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 242, in wrapped
    ret = await coro(*args, **kwargs)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "f:\Mahdi\Python\discord-server-copy-main\cogs\cloner_cog.py", line 128, in copy
    await function()
  File "f:\Mahdi\Python\discord-server-copy-main\modules\cloner.py", line 225, in clone_categories
    overwrites[self.mappings["roles"][role.id]] = permissions
               ~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
KeyError: 1130207478135652473

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ALMWSHOOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\bot.py", line 1169, in invoke
    await ctx.command.invoke(ctx)
  File "C:\Users\ALMWSHOOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 1026, in invoke
    await injected(*ctx.args, **ctx.kwargs)  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ALMWSHOOR\AppData\Local\Programs\Python\Python312\Lib\site-packages\discord\ext\commands\core.py", line 251, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: KeyError: 1130207478135652473
```

**Comment by itskekoff** [comment]
send me discord server where this error appears.
