### ISSUE TITLE
idk what is this error, please help me

### ISSUE THREAD

**Issue by Lore5666** [itskekoff/discord-server-copy#64]
13:50:42 | [HitFinger🌴/DEBUG] | Got overwrites mapping for channel #cand-manager
13:50:43 | [HitFinger🌴/DEBUG] | Created text channel #cand-manager | 1244981174896427128
13:50:45 | [HitFinger🌴/DEBUG] | Got overwrites mapping for channel #🎫 Supporto
13:50:48 | [HitFinger🌴/INFO] | Processing community settings
--- Logging error ---
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\logging\__init__.py", line 1113, in emit
    stream.write(msg + self.terminator)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 921-928: character maps to <undefined>
Call stack:
  File "C:\Users\loren\OneDrive\Desktop\discord-server-copy-main\main.py", line 183, in <module>
    bot.run(token, log_handler=file_handler, log_formatter=formatter)
  File "C:\Users\loren\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\client.py", line 1106, in run
    asyncio.run(runner())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 190, in run
    return runner.run(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 641, in run_until_complete
    self.run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\windows_events.py", line 321, in run_forever
    super().run_forever()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 608, in run_forever
    self._run_once()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\base_events.py", line 1936, in _run_once
    handle._run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.11_3.11.2544.0_x64__qbz5n2kfra8p0\Lib\asyncio\events.py", line 84, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\loren\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\client.py", line 637, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\loren\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\ext\commands\bot.py", line 251, in on_command_error
    _log.error('Ignoring exception in command %s', command, exc_info=exception)
Message: 'Ignoring exception in command %s'
Arguments: (<discord.ext.commands.core.Command object at 0x0000022B7367AA90>,)

**Comment by itskekoff** [comment]
install latest python from official website

**Comment by Lore5666** [comment]
same error

--- Logging error ---
Traceback (most recent call last):
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\logging\__init__.py", line 1163, in emit
    stream.write(msg + self.terminator)
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\encodings\cp1252.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeEncodeError: 'charmap' codec can't encode characters in position 921-928: character maps to <undefined>
Call stack:
  File "C:\Users\loren\OneDrive\Desktop\discord-server-copy-main\main.py", line 183, in <module>
    bot.run(token, log_handler=file_handler, log_formatter=formatter)
  File "C:\Users\loren\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\client.py", line 1106, in run
    asyncio.run(runner())
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 674, in run_until_complete
    self.run_forever()
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\asyncio\windows_events.py", line 322, in run_forever
    super().run_forever()
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 641, in run_forever
    self._run_once()
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 1987, in _run_once
    handle._run()
  File "C:\Users\loren\AppData\Local\Programs\Python\Python312\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\Users\loren\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\client.py", line 637, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\loren\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\ext\commands\bot.py", line 251, in on_command_error
    _log.error('Ignoring exception in command %s', command, exc_info=exception)
Message: 'Ignoring exception in command %s'
Arguments: (<discord.ext.commands.core.Command object at 0x00000193186F08C0>,)
