### ISSUE TITLE
Nothing Happens, I recieve this

### ISSUE THREAD

**Issue by roniferr** [itskekoff/discord-server-copy#77]
06:56:35 | [Updater/INFO] | No updates found.
06:56:35 | [Main/INFO] | Logging in discord account...
Traceback (most recent call last):
  File "C:\Users\ayeea\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\http.py", line 1058, in static_login
    data = await self.get_me()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ayeea\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\http.py", line 934, in request
    raise HTTPException(response, data)
discord.errors.HTTPException: 401 Unauthorized (error code: 0): 401: Unauthorized

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\ayeea\OneDrive\Desktop\discord-server-copy-main\main.py", line 180, in <module>
    bot.run(token, log_handler=file_handler, log_formatter=formatter)
  File "C:\Users\ayeea\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\client.py", line 1106, in run
    asyncio.run(runner())
  File "C:\Users\ayeea\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 194, in run
    return runner.run(main)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\ayeea\AppData\Local\Programs\Python\Python312\Lib\asyncio\runners.py", line 118, in run
    return self._loop.run_until_complete(task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ayeea\AppData\Local\Programs\Python\Python312\Lib\asyncio\base_events.py", line 687, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Users\ayeea\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\client.py", line 1095, in runner
    await self.start(token, reconnect=reconnect)
  File "C:\Users\ayeea\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\client.py", line 1025, in start
    await self.login(token)
  File "C:\Users\ayeea\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\client.py", line 867, in login
    data = await state.http.static_login(token.strip())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ayeea\OneDrive\Desktop\discord-server-copy-main\venv\Lib\site-packages\discord\http.py", line 1062, in static_login
    raise LoginFailure('Improper token has been passed') from exc
discord.errors.LoginFailure: Improper token has been passed

**Comment by anonymo006** [comment]
do u run this in python virtual environment?

**Comment by roniferr** [comment]
Yes I did run this in python virtual environment, and im using the token of my discord account
![image](https://github.com/user-attachments/assets/dddecd2b-b484-40a7-9432-bce093b938c4)

**Comment by shaovatwit** [comment]
Did it respond with "Logged on as <YourUsername> \nLoaded 1 extensions, with total of # commands?"

Also, I would keep your prefix as cp! and then in the random channel on the server you want to clone, execute cp!clone from=#. You may want to check you input your token into the config.json as well.
