### ISSUE TITLE
wont start

### ISSUE THREAD

**Issue by notugotskilz** [itskekoff/discord-server-copy#84]
01:28:35 | [Updater/INFO] | No updates found.
01:28:35 | [Main/INFO] | Logging in discord account...
Traceback (most recent call last):
  File "C:\Users\blaze\Downloads\discord-server-copy-main (1)\discord-server-copy-main\main.py", line 180, in <module>
    bot.run(token, log_handler=file_handler, log_formatter=formatter)
  File "C:\Python311\Lib\site-packages\discord\client.py", line 723, in run
    return future.result()
           ^^^^^^^^^^^^^^^
  File "C:\Python311\Lib\site-packages\discord\client.py", line 702, in runner
    await self.start(*args, **kwargs)
  File "C:\Python311\Lib\site-packages\discord\client.py", line 663, in start
    raise TypeError("unexpected keyword argument(s) %s" % list(kwargs.keys()))
TypeError: unexpected keyword argument(s) ['log_handler', 'log_formatter']

**Comment by itskekoff** [comment]
remove discord.py package using pip and run install from requirements.txt
